### DISCUSSION TITLE
Is it possible to render the QueryBuilder Rule header in one place and the Rule body in a totally different place ?

### DISCUSSION THREAD

**Discussion by keerthankrishna** [react-querybuilder/react-querybuilder#423] [Q&A] [answered]
I would like to have the _Rule header_ in one place (_example: top right corner of the screen_) and then when i hit "**+Rule**" or "**+Group**" I want the _Rule body_ to be rendered in the center of the screen. Is this possible ?

**Something like this:**
![image](https://user-images.githubusercontent.com/24373382/207776284-a01524c4-70f2-42b2-9c0d-7f108194cfb8.png)

**Comment by jakeboone02** [comment, marked as answer]
You can use `position: absolute` on the root `.ruleGroup-header` element to remove it from the normal layout flow.

[CodeSandbox link here](https://codesandbox.io/s/wandering-cdn-2ntzsb?file=/src/styles.scss). I used SCSS variables for consistency with the default styles. Let me know if you need a plain CSS version.

```scss
@import 'react-querybuilder/dist/query-builder.scss';

html {
  height: 100%;
}

body {
  margin: 0.5rem !important;
  height: 100%;
}

#root {
  display: flex;
  align-items: center;
  justify-content: center;
  height: 100%;
}

.queryBuilder > .ruleGroup > .ruleGroup-header {
  position:absolute;
  top: $rqb-spacing;
  right: $rqb-spacing;
  padding: $rqb-spacing;
  border-color: $rqb-border-color;
  border-style: $rqb-border-style;
  border-width: $rqb-border-width;
  border-radius: $rqb-border-radius;
  background-color: $rqb-background-color;
}
```

Since the root "+Group" button is outside the query builder boundaries, does that mean you don't want to allow sub-sub-groups? If so, you can hide the other "+Group" buttons with this CSS:

```css
.ruleGroup .ruleGroup .ruleGroup-addGroup {
  display: none;
}
```

**Reply by keerthankrishna** [reply]
This is great! 

If I am calling 2 QueryBuilders in the same page, can i assign separate classes to each of the headers by assigning a different _className_ ? Reason for this question is this: If i set a style for **.ruleGroup-header** class, then it gets applied to both the QueryBuilder components.

**Reply by keerthankrishna** [reply]
The answer to your question "_Since the root "+Group" button is outside the query builder boundaries, does that mean you don't want to allow sub-sub-groups?_" is "**Yes**". Thank you so much for answering these!

**Reply by jakeboone02** [reply]
> can i assign separate classes to each of the headers

Yes! Use the `header` property on the `controlClassnames` prop.

[CodeSandbox here](https://codesandbox.io/s/inspiring-diffie-o1bil4?file=/src/App.tsx).

```scss
.header1 { left: $rqb-spacing; }
.header1::before { content: 'Header 1'; }

.header2 { right: $rqb-spacing; }
.header2::before { content: 'Header 2'; }
```

```tsx
export const App = () => {
  const [query, setQuery] = useState(initialQuery);
  const [query2, setQuery2] = useState(initialQuery);

  return (
    <>
      <span>Query Generator 1</span>
      <QueryBuilder
        fields={fields}
        query={query}
        onQueryChange={q => setQuery(q)}
        controlClassnames={{
          header: 'header1',
        }}
      />
      <span>Query Generator 2</span>
      <QueryBuilder
        fields={fields}
        query={query2}
        onQueryChange={q => setQuery2(q)}
        controlClassnames={{
          header: 'header2',
        }}
      />
    </>
  );
};
```
