### DISCUSSION TITLE
Moving Rule button to the bottom of a query group.

### DISCUSSION THREAD

**Discussion by gramprakash** [react-querybuilder/react-querybuilder#496] [Q&A] [answered]
Hey guys,

I wanted to try and modify the CSS so that I could move the rule button to the bottom-left hand corner of a query group. I have tried multiple hacks, but it doesn't seem to work. Does anyone have any ideas as to how to modify the css and make it work? Thanks.

**Comment by jakeboone02** [comment]
I think the easiest way to do this would be to flip the order of the group header and body:

```css
.ruleGroup-header {
  order: 2;
}

.ruleGroup-body {
  order: 1;
}
```
