### ISSUE TITLE
feature add custom styles for the header of ruleGroup

### ISSUE THREAD

**Issue by KamiGim** [react-querybuilder/react-querybuilder#41]
like the one in https://dabernathy89.github.io/vue-query-builder/
![image](https://user-images.githubusercontent.com/17401507/30094855-122ea950-92f9-11e7-803b-fa7fa83eed06.png)

**Comment by pavanpodila** [comment]
Please try using the [controlClassNames prop](https://github.com/sapientglobalmarkets/react-querybuilder#controlclassnames-optional) and see if you can achieve the styling needed.

**Comment by snsheth55** [comment]
Hello, could you please provide an example of how to do custom styling as I am having difficulty changing the css on the various elements of the querybuilder. Thank you

**Comment by jakeboone02** [comment]
@snsheth55 You can use the built in class names in your CSS, or (as @pavanpodila pointed out) provide your own class names through the [controlClassnames prop](https://github.com/sapientglobalmarkets/react-querybuilder#controlclassnames-optional).  For example, to roughly imitate the styles above, add this after this library's distributed CSS:

```css
.ruleGroup {
  background-color: white;
}
.ruleGroup, .ruleGroup .ruleGroup, .ruleGroup .rule {
  border-radius: 4px;
  border: 1px solid #ddd;
  box-shadow: 0 1px 1px rgba(0,0,0,.05)
}
.ruleGroup .rule {
  background-color: #f5f5f5;
  border-left: 2px solid #00bcd4;
  padding: 1rem;
}
.ruleGroup .ruleGroup {
  border-left: 2px solid #8bc34a;
}
.ruleGroup-remove, .rule-remove {
  float: right;
}
.ruleGroup-combinators,
.ruleGroup-addRule,
.ruleGroup-addGroup,
.rule-fields,
.rule-operators,
.rule-value {
  background-color: white;
  border: 1px solid #ddd;
  border-radius: 4px;
  padding: 6px 12px;
}
.ruleGroup-remove, .rule-remove {
  background: transparent;
  border: none;
}
```
